name: '🐛 Bug Report'
description: Report a reproducible bug.
labels: ['🐛 Bug']
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our documentation, especially the [README](https://github.com/FelixLgr/logsnag-react/blob/master/README.md). It may contain information that helps you solve your issue.
        - Ensure your issue isn't already [reported](https://github.com/FelixLgr/logsnag-react/issues?utf8=%E2%9C%93&q=is%3Aissue).
        - Ensure it isn't already fixed in the latest logsnag-react version.
  - type: markdown
    attributes:
      value: '⚠️👆 Feel free to these instructions before submitting the issue 👆⚠️'
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 'To Reproduce'
      description: |
        Code snippet to reproduce, ideally if you can provide a live example in https://codesandbox.io/ sandbox or a repository that illustrates the issue.
    validations:
      required: false
  - type: textarea
    id: code-snippet
    attributes:
      label: 'Code snippet'
      render: js
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

